/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TopChartsImport } from './routes/top-charts'
import { Route as SongsImport } from './routes/songs'
import { Route as PlaylistsImport } from './routes/playlists'
import { Route as JustForYouImport } from './routes/just-for-you'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TopChartsRoute = TopChartsImport.update({
  id: '/top-charts',
  path: '/top-charts',
  getParentRoute: () => rootRoute,
} as any)

const SongsRoute = SongsImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsRoute = PlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRoute,
} as any)

const JustForYouRoute = JustForYouImport.update({
  id: '/just-for-you',
  path: '/just-for-you',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/just-for-you': {
      id: '/just-for-you'
      path: '/just-for-you'
      fullPath: '/just-for-you'
      preLoaderRoute: typeof JustForYouImport
      parentRoute: typeof rootRoute
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsImport
      parentRoute: typeof rootRoute
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsImport
      parentRoute: typeof rootRoute
    }
    '/top-charts': {
      id: '/top-charts'
      path: '/top-charts'
      fullPath: '/top-charts'
      preLoaderRoute: typeof TopChartsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/just-for-you': typeof JustForYouRoute
  '/playlists': typeof PlaylistsRoute
  '/songs': typeof SongsRoute
  '/top-charts': typeof TopChartsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/just-for-you': typeof JustForYouRoute
  '/playlists': typeof PlaylistsRoute
  '/songs': typeof SongsRoute
  '/top-charts': typeof TopChartsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/just-for-you': typeof JustForYouRoute
  '/playlists': typeof PlaylistsRoute
  '/songs': typeof SongsRoute
  '/top-charts': typeof TopChartsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/just-for-you' | '/playlists' | '/songs' | '/top-charts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/just-for-you' | '/playlists' | '/songs' | '/top-charts'
  id:
    | '__root__'
    | '/'
    | '/just-for-you'
    | '/playlists'
    | '/songs'
    | '/top-charts'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JustForYouRoute: typeof JustForYouRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SongsRoute: typeof SongsRoute
  TopChartsRoute: typeof TopChartsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JustForYouRoute: JustForYouRoute,
  PlaylistsRoute: PlaylistsRoute,
  SongsRoute: SongsRoute,
  TopChartsRoute: TopChartsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/just-for-you",
        "/playlists",
        "/songs",
        "/top-charts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/just-for-you": {
      "filePath": "just-for-you.tsx"
    },
    "/playlists": {
      "filePath": "playlists.tsx"
    },
    "/songs": {
      "filePath": "songs.tsx"
    },
    "/top-charts": {
      "filePath": "top-charts.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
